### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by marcotini** [stelgenhof/opensubtitles#1]
When I insert the IMDB Movie Number here what's happen: 

```
PHP Fatal error:  Uncaught exception 'Dotenv\Exception\InvalidPathException' with message 'Unable to read the environment file at /var/www/html/opensubtitles/.env.' in /var/www/html/opensubtitles/vendor/vlucas/phpdotenv/src/Loader.php:75
Stack trace:
#0 /var/www/html/opensubtitles/vendor/vlucas/phpdotenv/src/Loader.php(52): Dotenv\Loader->ensureFileIsReadable()
#1 /var/www/html/opensubtitles/vendor/vlucas/phpdotenv/src/Dotenv.php(91): Dotenv\Loader->load()
#2 /var/www/html/opensubtitles/vendor/vlucas/phpdotenv/src/Dotenv.php(48): Dotenv\Dotenv->loadData()
#3 /var/www/html/opensubtitles/opensubtitles.php(37): Dotenv\Dotenv->load()
#4 {main}
  thrown in /var/www/html/opensubtitles/vendor/vlucas/phpdotenv/src/Loader.php on line 75

```

**Comment by marcotini** [comment]
My bad.

**Comment by stelgenhof** [comment]
No problem! :)
